# GoodsCtrl
menu:
  -
    ctrl: GoodsCtrl
    text: 图书管理
    url: goods      # 全局必须唯一
    icon:
    id:         # 对应数据库权限控制表中的id， 各功能设计者自己编写，全局必须唯一
    menuList:
      - text: 获取图书列表数据
        url: getGoods   # 本菜单域内，必须唯一
        icon:
        method:
        id:
      - text: 图书编辑
        url: edit
        icon:
        method:
        id:

  -
    ctrl: GoodsTypeCtrl
    text: 图书类别管理
    url: goodsType
    icon:
    id:
    menuList:
      - text: 获取图书类别列表数据
        url: getGoodsType
        icon:
        method:
        id:
      - text: 图书类别编辑
        url: edit
        icon:
        method:
        id:
      - text: 增加图书类别
        url: add
        icon:
        method:
        id:
      - text: 删除图书类别
        url: del
        icon:
        method:
        id: